#TITLE_BACKGROUND_COLOR = 'black'
#TITLE_TEXT_COLOR = 'green'
TITLE_PADX = 20
TITLE_PADY = 20
TITLE_FONT = 'ubuntu 20'
TITLE_RELIEF = 'raised'

##FRAME1_BG_COLOR = 'black'
##FRAME1_FG_COLOR = 'green'
FRAME1_RELIEF = 'ridge'
FRAME1_PADX = 10
FRAME1_PADY = 10
FRAME1_FONT = 'ubuntu 12'

FRAME1_LABEL_TEXT = 'Characters'
##FRAME1_LABEL_BG_COLOR = 'black'
##FRAME1_LABEL_FG_COLOR = 'green'
FRAME1_LABEL_TOOLTIP = 'The set of letters symbols and numbers\n to start out with when creating a\n password list'

FRAME1_COMBO_BOX_KEY = 'SETNAME'
FRAME1_COMBO_BOX_EXPAND_Y = True

FRAME1_HIDDEN_ENTRY_BOX_KEY = 'HIDDENCHARSET'
FRAME1_HIDDEN_ENTRY_BOX_ENABLE_EVENTS = True
FRAME1_HIDDEN_ENTRY_BOX_PAD_X = 10
FRAME1_HIDDEN_ENTRY_BOX_PAD_Y = 10

FRAME1_CHARACTERSET_STATUS_BAR_SIZE_X = 90
FRAME1_CHARACTERSET_STATUS_BAR_SIZE_Y = 1
FRAME1_CHARACTERSET_STATUS_BAR_KEY = 'STATUSSET'
FRAME1_CHARACTERSET_STATUS_BAR_FONT = 'ubuntu 10'
##FRAME1_CHARACTERSET_STATUS_BAR_BG_COLOR = 'black'
##FRAME1_CHARACTERSET_STATUS_BAR_FG_COLOR = 'green'
FRAME1_CHARACTERSET_STATUS_BAR_JUSTIFICATION = 'center'

FRAME2_EXCEPTIONS_LABEL_TEXT = 'Exceptions'
FRAME2_EXCEPTIONS_LABEL_FONT = 'ubuntu 10'

FRAME2_EXCEPTIONS_ENTRY_BOX_KEY = 'EXCEPTIONS'
FRAME2_EXCEPTIONS_ENTRY_BOX_FONT = 'ubuntu 10'

FRAME2_EXCEPTIONS_STATUS_BAR_SIZE_X = 90
FRAME2_EXCEPTIONS_STATUS_BAR_SIZE_Y = 1
FRAME2_EXCEPTIONS_STATUS_BAR_KEY = 'STATUSEXCEPTIONS'
FRAME2_EXCEPTIONS_STATUS_BAR_FONT = 'ubuntu 10'
##FRAME2_EXCEPTIONS_STATUS_BAR_BG_COLOR = 'black'
##FRAME2_EXCEPTIONS_STATUS_BAR_FG_COLOR = 'green'

##FRAME2_BG_COLOR = 'black'
##FRAME2_FG_COLOR = 'green'
FRAME2_RELIEF = 'ridge'
FRAME2_PADX = 10
FRAME2_PADY = 10
FRAME2_FONT = 'ubuntu 10'

FRAME3_OUTFILE_LABEL_TEXT = 'Outfile:'
FRAME3_OUTFILE_LABEL_FONT = 'ubuntu 10'

FRAME3_OUTFILE_ENTRY_BOX_KEY = 'OUTFILEENTRY'

FRAME3_FILEBROWSE_KEY = 'OUTFILE'
FRAME3_FILEBROWSE_FONT = 'ubuntu 10'

FRAME3_ELEMENT_JUSTIFICATION = 'center'
##FRAME3_BG_COLOR = 'black'
##FRAME3_FG_COLOR = 'green'
FRAME3_RELIEF = 'ridge'
FRAME3_FONT = 'ubuntu 10'
FRAME3_PADX = 10
FRAME3_PADY = 10

##WINDOW_BG_COLOR = 'black'